version: '2'

services:
  api:
    build: api
    ports:
      - 5000:5000
    environment:
      MYSQL_USER: "${MYSQL_USER}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
    links:
      - db
    depends_on:
      - db
      - webui
  db:
    image: mysql:5.7
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: "gears"
      MYSQL_USER: "${MYSQL_USER}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
    volumes:
      - ./database/init:/docker-entrypoint-initdb.d/:ro
      - ./database/mysql:/var/lib/mysql
  webui:
    build: webui
    environment:
      - NGINX_HOST="${NGINX_HOST}""
      - NGINX_PORT=80
    ports:
      - 80:80
    volumes:
      - ./webui/content:/usr/share/nginx/html
