version: '2'

services:
  api:
    build: api
    ports:
      - 5000:5000
    environment:
      - MYSQL_ROOT_PASSWORD="${MYSQL_ROOT_PASSWORD}"
    links:
      - db
    depends_on:
      - db
      - webui
  db:
    image: mysql:5.6
    ports:
      - 3306:3306
    environment:
      - MYSQL_DATABASE=gears
      - MYSQL_ROOT_HOST=%
      - MYSQL_ROOT_PASSWORD="${MYSQL_ROOT_PASSWORD}"
    volumes:
      - ./database/mysql:/var/lib/mysql
  webui:
    build: webui
    environment:
      - NGINX_HOST="${NGINX_HOST}""
      - NGINX_PORT=80
    ports:
      - 80:80
    volumes:
      - ./webUI/content:/usr/share/nginx/html
