version: '2'

services:
  api:
    build: api
    ports:
      - 5000:5000
    depends_on:
      - db
      - webui
  db:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - ./database:/data/db
  webui:
    build: webui
    ports:
      - 80:80
    volumes:
      - ./webUI/content:/usr/share/nginx/html
